### ISSUE TITLE
movement is backwards 

### ISSUE THREAD

**Issue by JasonLovesDoggo** [robert-abraham/PyWeek-33-March#35]

**Comment by SoupySoups** [comment]
How so?

**Comment by JasonLovesDoggo** [comment]
Not sure if you want it bc it looks odd but you can fix it by setting main.py L#82-85 to
  level.movement.add(pygame.K_DOWN, game_input.Movement.UP)
    level.movement.add(pygame.K_s, game_input.Movement.UP)
    level.movement.add(pygame.K_UP, game_input.Movement.DOWN)
    level.movement.add(pygame.K_w, game_input.Movement.DOWN)

**Comment by SoupySoups** [comment]
oh you think its backwards cause the player is facing that way, i see.

**Comment by SoupySoups** [comment]
no i just havent implemented player turning yet

**Comment by JasonLovesDoggo** [comment]
yes, but fixing it also feels off

**Comment by JasonLovesDoggo** [comment]
I'll leave the final decision to you

**Comment by SoupySoups** [comment]
ill see once animations get done
